### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by optimaljonathan** [nepada/phone-number-doctrine#1]
The configuration for bootstrap has typos. It should be:

> \Doctrine\DBAL\Types\Type::addType(
>     \Nepada\PhoneNumberDoctrine\PhoneNumberType::NAME,
>     \Nepada\PhoneNumberDoctrine\PhoneNumberType::class
> );

**Comment by xificurk** [comment]
fixed #dfd230646ed3ef81bea0ddded2fdf26a943c5086
